#pragma once

namespace Engine
{
	enum class PROTOTYPE { TYPE_GAMEOBJECT, TYPE_COMPONENT };

	typedef enum COLLIDERGROUP { CG_PLAYER, CG_MONSTER, CG_WEAPON, 
								CG_PLAYER_PROJECTILE_CUBE, CG_PLAYER_PROJECTILE_SPHERE,
								CG_MONSTER_PROJECTILE_CUBE, CG_MONSTER_PROJECTILE_SPHERE,
								CG_STRUCTURE_WALL, CG_STRUCTURE_FLOOR,  CG_UI, CG_SHOP, CG_END } ColliderGroup;
	 
}